tap "felixkratz/formulae"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "koekeishiya/formulae"
tap "puma/puma"
brew "python@3.11"
brew "ansible"
brew "libgit2"
brew "bat"
brew "cmake"
brew "direnv"
brew "duf"
brew "exa"
brew "fd"
brew "fish"
brew "fisher"
brew "fzf"
brew "gh"
brew "git"
brew "unbound"
brew "gnutls"
brew "gnupg"
brew "go"
brew "protobuf"
brew "swift-protobuf"
brew "grpc-swift"
brew "hopenpgp-tools"
brew "htop"
brew "jpeg"
brew "llvm"
brew "lsd"
brew "luv"
brew "mackup"
brew "mas"
brew "neovim"
brew "ninja"
brew "nmap"
brew "node"
brew "pinentry-mac"
brew "prettier"
brew "pyenv"
brew "python@3.10"
brew "ruby-build"
brew "rbenv"
brew "ripgrep"
brew "shadowenv"
brew "starship"
brew "swift-format", args: ["HEAD"]
brew "swiftformat"
brew "swiftlint"
brew "tmux"
brew "tree"
brew "typescript"
brew "wget"
brew "yarn"
brew "ykman"
brew "ykpers"
brew "heroku/brew/heroku"
brew "jesseduffield/lazygit/lazygit"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "puma/puma/puma-dev"
cask "1password"
cask "autodesk-fusion360"
cask "discord"
cask "docker"
cask "elgato-control-center"
cask "firefox"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "font-martian-mono"
cask "imageoptim"
cask "iterm2"
cask "keepingyouawake"
cask "kitty"
cask "little-snitch"
cask "loom"
cask "lunar"
cask "obs"
cask "obsidian"
cask "raspberry-pi-imager"
cask "raycast"
cask "screen-studio"
cask "sensei"
cask "spaceman"
cask "spotify"
cask "telegram"
cask "transmission"
cask "via"
cask "visual-studio-code"
cask "vlc"
cask "webex"
cask "zoom"
mas "AdGuard for Safari", id: 1440147259
mas "Bear", id: 1091189122
mas "Cardhop", id: 1290358394
mas "DaisyDisk", id: 411643860
mas "DetailsPro", id: 1524366536
mas "Developer", id: 640199958
mas "Disk Speed Test", id: 425264550
mas "Fabula", id: 1591155142
mas "Fantastical", id: 975937182
mas "Ivory", id: 6444602274
mas "Pixelmator Pro", id: 1289583905
mas "Playgrounds", id: 1496833156
mas "Slack", id: 803453959
mas "Stellar", id: 1566795636
mas "TestFlight", id: 899247664
mas "Things", id: 904280696
mas "WhatsApp", id: 1147396723
vscode "alefragnani.project-manager"
vscode "bradlc.vscode-tailwindcss"
vscode "bung87.rails"
vscode "bung87.vscode-gemfile"
vscode "Catppuccin.catppuccin-vsc"
vscode "dbaeumer.vscode-eslint"
vscode "donjayamanne.python-extension-pack"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "GitHub.copilot"
vscode "GitHub.copilot-chat"
vscode "GitHub.copilot-labs"
vscode "GitHub.heygithub"
vscode "github.vscode-github-actions"
vscode "GitHub.vscode-pull-request-github"
vscode "golang.go"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "rebornix.ruby"
vscode "redhat.vscode-yaml"
vscode "sianglim.slim"
vscode "sswg.swift-lang"
vscode "teabyii.ayu"
vscode "vadimcn.vscode-lldb"
vscode "vscode-icons-team.vscode-icons"
vscode "vscodevim.vim"
vscode "Vue.volar"
vscode "wingrunr21.vscode-ruby"
vscode "yzhang.markdown-all-in-one"
vscode "zxh404.vscode-proto3"
