#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#

# The --load-sa line loads the scripting addition, and it's currently
# disabled anyway
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.8
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.20
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  6
yabai -m config bottom_padding               6
yabai -m config left_padding                 6
yabai -m config right_padding                6
yabai -m config window_gap                   6


# rules to ignore some apps in tiling

# Finder, Safari, and Mail.app settings windows
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off

# Mac OS Ventura renamed System Preferences to Settings
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="System Settings" app="System Settings" manage=off
yabai -m rule --add label="Mail.app" app="Mail" title="^(General|Accounts|Junk|Fonts|Viewing|Composing|Signatures|Rules|Extensions|Privacy)" manage=off
yabai -m rule --add label="Calendar" app="Calendar" title="^(General|Accounts|Alerts|Advanced)" manage=off

yabai -m rule --add label="Messages" app="Messages" manage=off
yabai -m rule --add label="Tips" app="Tips" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

yabai -m rule --add label="Music" app="Music" manage=off

yabai -m rule --add label="Simulator" app="Simulator" manage=off
yabai -m rule --add label="Zoom" app="zoom.us" manage=off
yabai -m rule --add label="Zoom Meeting" app="zoom.us" title="^Zoom Meeting" manage=on
yabai -m rule --add label="Facetime" app="FaceTime" manage=off
yabai -m rule --add label="Archive Utility" app="Archive Utility" manage=off

## Apps that should not be tiled & small utility apps
yabai -m rule --add label="Mullvad VPN" app="Mullvad VPN" manage=off
yabai -m rule --add label="Logi Options" app="Logi Options+" manage=off
yabai -m rule --add label="1Password" app="1Password" manage=off
yabai -m rule --add label="Raycast" app="Raycast" manage=off
yabai -m rule --add label="Daisy Disk" app="DaisyDisk" manage=off
yabai -m rule --add label="Battle.net" app="Battle.net" manage=off
yabai -m rule --add label="Loom" app="Loom" manage=off
yabai -m rule --add label="Spaceman" app="Spaceman" manage=off
yabai -m rule --add label="Lunar" app="Lunar" manage=off
yabai -m rule --add label="Ivory" app="Ivory" manage=off
yabai -m rule --add label="Webex" app="Webex" manage=off
yabai -m rule --add label="Balena Etcher" app="balenaEtcher" manage=off

yabai -m rule --add label="Fantastical" app="Fantastical" manage=off
yabai -m rule --add label="Fantastical Settings" app="Fantastical" title="^(General|Appearance|Alerts|Accounts|Calendars|Openings|Weather|Advanced)" manage=off
yabai -m rule --add label="Fantastical Helper" app="Fantastical Helper" manage=off
yabai -m rule --add label="Cardhop" app="Cardhop" manage=off

yabai -m rule --add label="Spotify" app="Spotify" manage=off

yabai -m rule --add label="Okta Verify" app="Okta Verify" manage=off

yabai -m rule --add label="Arc" app="Arc" title="^(Natik|General|Max|Profiles|Shortcuts|Links|Advanced)" manage=off


echo "yabai configuration loaded.."
